{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.6.8"
    },
    "colab": {
      "name": "data_operations.ipynb",
      "provenance": [],
      "include_colab_link": true
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/red-rising/LIAR-PLUS/blob/master/data_operations.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "epyBo-BfSVoH",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "from datetime import *\n",
        "import math\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import random"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "1a0WaYQESVoP",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Point:\n",
        "    pass\n",
        "class Interval:\n",
        "    pass\n",
        "class Rectangular_Region:\n",
        "    pass\n",
        "class Spatial_Segmentation:\n",
        "    pass\n",
        "class Temporal_Segmentation:\n",
        "    pass\n",
        "class Earthquake:\n",
        "    pass\n",
        "\n",
        "def create_frequency_matrix(earthquakes, subregions, subintervals):\n",
        "    pass\n",
        "def extract_from_csv(file, time_converter_function):\n",
        "    pass\n",
        "def time_from_string_usgs(time_str):\n",
        "    pass"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "B4ynWsPkSVoU",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Point:\n",
        "    \n",
        "    \"\"\"\n",
        "    An instance of this class contains a latitude and a longitude.\n",
        "    It will be printed as \"(<latidude>, <longitude>)\"\n",
        "    \"\"\"\n",
        "    \n",
        "    def __init__(self, latitude, longitude):\n",
        "        self.latitude = latitude\n",
        "        self.longitude = longitude\n",
        "    \n",
        "    def __str__(self):\n",
        "        return \"({}, {})\".format(self.latitude, self.longitude)\n",
        "\n",
        "#SAMPLE USAGE\n",
        "\n",
        "# point = Point(34.6, 78.6)\n",
        "# print(point)"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "nLz_QTHoSVoZ",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Rectangular_Region:\n",
        "    \n",
        "    \"\"\"\n",
        "    MEMBER FIELDS:\n",
        "    vertices: a 2-tuple (Point, Point). \n",
        "    \n",
        "    NOTE : The latitude and longitude values at vertices[0] must be less than or equal to\n",
        "           those at vertices[1].\n",
        "    \"\"\"\n",
        "    \n",
        "    def __init__(self, vertices):\n",
        "        \n",
        "        point1 = vertices[0]\n",
        "        point2 = vertices[1]\n",
        "        \n",
        "        assert(point1.latitude < point2.latitude and point1.longitude < point2.longitude)\n",
        "        \n",
        "        \n",
        "        self.vertices = vertices\n",
        "        self.height = point2.latitude - point1.latitude\n",
        "        self.width = point2.longitude - point1.longitude\n",
        "        \n",
        "    def __str__(self):\n",
        "        \n",
        "        vertices = self.vertices\n",
        "        point1 = vertices[0]\n",
        "        point2 = vertices[1]\n",
        "        return_str = \"Region bounded between Latitudes ({}, {}); Longitudes ({}, {})\".format(point1.latitude, point2.latitude, point1.longitude, point2.longitude)\n",
        "        return return_str\n",
        "    \n",
        "    \"\"\"\n",
        "    MEMBER FUNCTIONS:\n",
        "    \n",
        "    Rectangular_Region.contains(coordinates) : checks if a given point is \n",
        "                                               contained in the region\n",
        "    \n",
        "    Arguments:\n",
        "    \n",
        "    coordinates : an instance of Coordinates\n",
        "    \"\"\"\n",
        "    def contains(self, point):\n",
        "        point_lat = point.latitude\n",
        "        point_long = point.longitude\n",
        "        \n",
        "        vertices = self.vertices\n",
        "        point1 = vertices[0]\n",
        "        point2 = vertices[1]\n",
        "        \n",
        "        h_bounded = point_lat >= point1.latitude and point_lat <= point2.latitude\n",
        "        v_bounded = point_long >= point1.longitude and point_long <= point2.longitude\n",
        "        \n",
        "        return h_bounded and v_bounded\n",
        "    \n",
        "# SAMPLE USAGE\n",
        "\n",
        "# point1 = Point(34.6, 78.9)\n",
        "# point2 = Point(56.5, 89.6)\n",
        "# vertices = (point1, point2)\n",
        "\n",
        "# point3 = Point(35, 80)\n",
        "# point4 = Point(30, 75)\n",
        "\n",
        "# region = Rectangular_Region(vertices)\n",
        "# print(region)\n",
        "# print(region.height)\n",
        "# print(region.width)\n",
        "# print(region.contains(point3))\n",
        "# print(region.contains(point4))"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "wP3alubNSVoh",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Spatial_Segmentation:\n",
        "    \n",
        "    \"\"\"\n",
        "    This class handles the process of dividing a region into subregions.\n",
        "    \n",
        "    MEMBER FUNCTIONS : regions\n",
        "    \"\"\"\n",
        "    def __init__(self, region, rows, cols):\n",
        "        \n",
        "        self.subregion_height = region.height / rows\n",
        "        self.subregion_width = region.width / cols\n",
        "        \n",
        "        point1, point2 = region.vertices\n",
        "        \n",
        "        self.origin = point1\n",
        "        self.end = point2\n",
        "        latitude1, longitude1 = (point1.latitude, point1.longitude)\n",
        "        latitude2, longitude2 = (point2.latitude, point2.longitude)\n",
        "        \n",
        "        subregions = []\n",
        "        \n",
        "        for i in range(rows):\n",
        "            row = []\n",
        "            begin_lat = latitude1 + self.subregion_height * i\n",
        "            end_lat = begin_lat + self.subregion_height\n",
        "            \n",
        "            for j in range(cols): \n",
        "                begin_long = longitude1 + self.subregion_width * j\n",
        "                end_long = begin_long + self.subregion_width\n",
        "                \n",
        "                vertices = (Point(begin_lat, begin_long), Point(end_lat, end_long))\n",
        "                subregion = Rectangular_Region(vertices)\n",
        "                \n",
        "                row.append(subregion)\n",
        "            \n",
        "            subregions.append(row)\n",
        "        \n",
        "        self.matrix = subregions\n",
        "        self.height = rows\n",
        "        self.width = cols\n",
        "        \n",
        "    def __iter__(self):\n",
        "        \n",
        "        for i in xrange(self.height):\n",
        "            for j in xrange(self.width):\n",
        "                yield self.matrix[i][j]\n",
        "                \n",
        "    def __getitem__(self, i):\n",
        "        return self.matrix[i]\n",
        "            \n",
        "    \n",
        "    def __str__(self):\n",
        "        \n",
        "        return_str = \"Listing {}*{} subregions:\\n\".format(self.height, self.width)\n",
        "        \n",
        "        for i in range(self.height):\n",
        "            for j in range(self.width):\n",
        "                return_str += str(self.matrix[i][j]) + \"\\n\"\n",
        " \n",
        "        return return_str\n",
        "\n",
        "    \n",
        "    def __len__(self):\n",
        "        \n",
        "        return len(self.matrix)\n",
        "                \n",
        "                \n",
        "#SAMPLE USAGE\n",
        "\n",
        "# print(region)\n",
        "\n",
        "# subregions = Spatial_Segmentation(region, 3, 4)\n",
        "# print(subregions)     \n",
        "# print(subregions[2][3]) \n",
        "# print(subregions.origin)\n",
        "# print(subregions.end)          "
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "cx_wYLIESVom",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Interval:\n",
        "    \n",
        "    \"\"\"\n",
        "    MEMBER FIELDS:\n",
        "    \n",
        "    start_time, end_time : should be instances of the datetime class\n",
        "    \"\"\"\n",
        "    \n",
        "    def __init__(self, start_time, end_time):\n",
        "        assert(isinstance(start_time, datetime) and isinstance(end_time, datetime))\n",
        "        self.start = start_time\n",
        "        self.end = end_time\n",
        "    \n",
        "    def __str__(self):\n",
        "        return \"({}, {})\".format(self.start, self.end)\n",
        "    \n",
        "    \n",
        "    def contains(self, timestamp):\n",
        "        assert(isinstance(timestamp, datetime))\n",
        "        \n",
        "        return self.start <= timestamp and self.end >= timestamp\n",
        "\n",
        "#SAMPLE USAGE\n",
        "\n",
        "# time_x = datetime(2020, 2, 10, 17, 15, 20)\n",
        "# time_y = datetime(2021, 4, 11, 19, 45, 8)\n",
        "# interval = Interval(time_x, time_y)\n",
        "# print(interval)\n",
        "\n",
        "# time1 = datetime(2019, 4, 5)\n",
        "# time2 = datetime(2020, 3, 11)\n",
        "\n",
        "# print(interval.contains(time1))\n",
        "# print(interval.contains(time2))"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6HuqQaHjSVos",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Temporal_Segmentation:\n",
        "    \n",
        "    def __init__(self, time_window, num_segments):\n",
        "        \n",
        "        assert(isinstance(time_window, Interval))\n",
        "        \n",
        "        self.num_segments = num_segments\n",
        "        segment_length = (time_window.end - time_window.start) / num_segments\n",
        "        segments = []\n",
        "        \n",
        "        self.begin = time_window.start\n",
        "        self.end = time_window.end\n",
        "        \n",
        "        for i in range(num_segments):\n",
        "            \n",
        "            start = time_window.start + i * segment_length\n",
        "            end = start + segment_length\n",
        "            segment = Interval(start, end)\n",
        "            segments.append(segment)\n",
        "        \n",
        "        self.matrix = segments\n",
        "        self.segment_length = segment_length\n",
        "        \n",
        "    def __str__(self):\n",
        "        \n",
        "        return_str = \"\"\n",
        "\n",
        "        for segment in self.matrix:\n",
        "            return_str += str(segment) + \"\\n\"\n",
        "    \n",
        "        return return_str\n",
        "    \n",
        "    def __iter__(self):\n",
        "        \n",
        "        for i in xrange(self.num_segments):\n",
        "            yield self.matrix[i]\n",
        "    \n",
        "    def __getitem__(self, i):\n",
        "        \n",
        "        return self.matrix[i]\n",
        "    \n",
        "    def __len__(self):\n",
        "        return len(self.matrix)\n",
        "\n",
        "# SAMPLE USAGE\n",
        "\n",
        "# print(interval)\n",
        "# print()\n",
        "# subintervals = Temporal_Segmentation(interval, 4)\n",
        "# print(subintervals)\n",
        "# print(len(subintervals))"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "scrolled": true,
        "id": "h8DUu79_SVoz",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Earthquake:\n",
        "    \n",
        "    def __init__(self, timestamp, point, magnitude = None):\n",
        "        \n",
        "        assert(isinstance(timestamp, datetime))\n",
        "        assert(isinstance(point, Point))\n",
        "        \n",
        "        self.timestamp = timestamp\n",
        "        self.location = point\n",
        "        self.magnitude = magnitude\n",
        "        \n",
        "    def __str__(self):\n",
        "        \n",
        "        return_str = \"Time : {}, Location : ({}, {})\".format(self.timestamp, self.location.latitude, self.location.longitude)\n",
        "        \n",
        "        if self.magnitude is not None:\n",
        "            return_str += \", Magnitude : {}\".format(self.magnitude)\n",
        "        return return_str\n",
        "    \n",
        "    \n",
        "    \"\"\"\n",
        "    Given segments - a partition of a time interval into subintervals, this function\n",
        "                     returns the index of the segment that this particular instance\n",
        "                     falls into.\n",
        "    \"\"\"\n",
        "    def time_segment(self, segments):\n",
        "        \n",
        "        assert(isinstance(segments, Temporal_Segmentation))\n",
        "        \n",
        "        index = int((self.timestamp - segments[0].start) / segments.segment_length)\n",
        "#         print(index)\n",
        "        assert(segments[index].contains(self.timestamp))\n",
        "        return index\n",
        "    \n",
        "    def space_segment(self, segments):\n",
        "        \n",
        "        assert(isinstance(segments, Spatial_Segmentation))\n",
        "        \n",
        "        latitude = self.location.latitude\n",
        "        longitude = self.location.longitude\n",
        "        \n",
        "        origin_lat = segments[0][0].vertices[0].latitude\n",
        "        origin_long = segments[0][0].vertices[0].longitude\n",
        "        \n",
        "        i = int((latitude - origin_lat) / segments.subregion_height)\n",
        "        j = int((longitude - origin_long) / segments.subregion_width)\n",
        "#         print(i, j)\n",
        "#         print(segments[i][j])\n",
        "        assert(segments[i][j].contains(self.location))\n",
        "        \n",
        "        return (i, j)\n",
        "        \n",
        "# SAMPLE USAGE\n",
        "\n",
        "# timestamp = datetime(2020, 2, 26)\n",
        "# location = Point(56.6, 45.5)\n",
        "# earthquake = Earthquake(timestamp, location)\n",
        "# print(earthquake)\n",
        "\n",
        "# time1 = datetime(2019, 3, 4)\n",
        "# time2 = datetime(2021, 4, 3)\n",
        "\n",
        "# interval = Interval(time1, time2)\n",
        "# subintervals = Temporal_Segmentation(interval, 10)\n",
        "# print(subintervals)\n",
        "# print(earthquake.time_segment(subintervals))\n",
        "\n",
        "# point1 = Point(23, 23)\n",
        "# point2 = Point(70, 70)\n",
        "# vertices = (point1, point2)\n",
        "# region = Rectangular_Region(vertices)\n",
        "# subregions = Spatial_Segmentation(region, 2, 3)\n",
        "# print(region)\n",
        "# print(subregions)\n",
        "# print(earthquake.space_segment(subregions))"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "TrkF5FLySVo4",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "def extract_from_csv(file, time_converter_function):\n",
        "    \n",
        "    df = pd.read_csv(file)\n",
        "#     print(df.head())\n",
        "    df = df[[\"time\", \"latitude\", \"longitude\", \"mag\"]]\n",
        "    \n",
        "    earthquakes = []\n",
        "    \n",
        "    for i in range(len(df)):\n",
        "        \n",
        "        time = df[\"time\"][i]\n",
        "        latitude = df[\"latitude\"][i]\n",
        "        longitude = df[\"longitude\"][i]\n",
        "        magnitude = df[\"mag\"][i]\n",
        "        \n",
        "        time = time_converter_function(time)\n",
        "        latitude = float(latitude)\n",
        "        longitude = float(longitude)\n",
        "        point = Point(latitude, longitude)\n",
        "        magnitude = float(magnitude)\n",
        "        \n",
        "        earthquake = Earthquake(time, point, magnitude)\n",
        "        earthquakes.append(earthquake)\n",
        "    \n",
        "    earthquakes.sort(key = lambda x : x.timestamp)\n",
        "    return earthquakes\n",
        "\n",
        "        \n",
        "# SAMPLE USAGE\n",
        "\n",
        "# earthquakes = extract_from_csv(\"india_1950_2020.csv\", time_from_string_usgs)\n",
        "# print(earthquakes[0])"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "lxEhWPO3SVo8",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "def time_from_string_usgs(time_str):\n",
        "    \n",
        "    tokens = time_str.split(\"T\")\n",
        "    \n",
        "    date = tokens[0]\n",
        "    time = tokens[1]\n",
        "    \n",
        "    tokens = date.split(\"-\")\n",
        "    year = int(tokens[0])\n",
        "    month = int(tokens[1])\n",
        "    day = int(tokens[2])\n",
        "    \n",
        "    tokens = time.split(\":\")\n",
        "    hour = int(tokens[0])\n",
        "    minute = int(tokens[1])\n",
        "    second = int(tokens[2][:2])\n",
        "    \n",
        "    return datetime(year, month, day, hour, minute, second)\n",
        "\n",
        "# print(\"reload successful\")\n",
        "\n",
        "# SAMPLE USAGE\n",
        "\n",
        "# print(time_from_string_usgs(\"1950-02-26T03:35:46.000Z\"))"
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}